### ISSUE TITLE
Big_dogbot_64 BN: Invalid .json flag MOLLE

### ISSUE THREAD

**Issue by MisterWytt** [cataclysmroguelikegallery/Cata-Rogall-Modpack#134]
This error seems to pop up whenever I'm "e"xamining my surroundings or "v"iewing items from a distance. It took me a bit to re-create since it seemed to show up whenever it liked, but I finally reliably pinpointed it to this mod when doing Prison scenarios. Chaosvolt theorizes it's some leftover pocket data from DDA mixed into BN, but I'm not sure. Would love to see this found since you can't space bar it away, it requires you to "i"gnore it.
![Molle](https://github.com/cataclysmroguelikegallery/Cata-Rogall-Modpack/assets/46728252/a045b1fb-b1fb-47fd-be68-34cba08d9e28)

**Comment by scarf005** [comment]
strange, it doesn't error on my machine.
my guess is it's because of some load order issue the flags are used before its declaration.
